from .sdds import SDDS, load, loadSparse, loadLastRows, save, sdds_data_type_to_string, sdds_data_type_to_short_string, sdds_short_string_to_data_type, demo1, demo2, demo3, demo4, demo5, demo6, read, write


# Expose all constants from sdds.py
SDDS_VERBOSE_PrintErrors = SDDS.SDDS_VERBOSE_PrintErrors
SDDS_EXIT_PrintErrors = SDDS.SDDS_EXIT_PrintErrors
SDDS_CHECK_OKAY = SDDS.SDDS_CHECK_OKAY
SDDS_CHECK_NONEXISTENT = SDDS.SDDS_CHECK_NONEXISTENT
SDDS_CHECK_WRONGTYPE = SDDS.SDDS_CHECK_WRONGTYPE
SDDS_CHECK_WRONGUNITS = SDDS.SDDS_CHECK_WRONGUNITS
SDDS_LONGDOUBLE = SDDS.SDDS_LONGDOUBLE
SDDS_DOUBLE = SDDS.SDDS_DOUBLE
SDDS_REAL64 = SDDS.SDDS_REAL64
SDDS_FLOAT = SDDS.SDDS_FLOAT
SDDS_REAL32 = SDDS.SDDS_REAL32
SDDS_LONG64 = SDDS.SDDS_LONG64
SDDS_INT64 = SDDS.SDDS_INT64
SDDS_ULONG64 = SDDS.SDDS_ULONG64
SDDS_UINT64 = SDDS.SDDS_UINT64
SDDS_LONG = SDDS.SDDS_LONG
SDDS_INT32 = SDDS.SDDS_INT32
SDDS_ULONG = SDDS.SDDS_ULONG
SDDS_UINT32 = SDDS.SDDS_UINT32
SDDS_SHORT = SDDS.SDDS_SHORT
SDDS_INT16 = SDDS.SDDS_INT16
SDDS_USHORT = SDDS.SDDS_USHORT
SDDS_UINT16 = SDDS.SDDS_UINT16
SDDS_STRING = SDDS.SDDS_STRING
SDDS_CHARACTER = SDDS.SDDS_CHARACTER
SDDS_NUM_TYPES = SDDS.SDDS_NUM_TYPES
SDDS_BINARY = SDDS.SDDS_BINARY
SDDS_ASCII = SDDS.SDDS_ASCII
SDDS_FLUSH_TABLE = SDDS.SDDS_FLUSH_TABLE

__all__ = [
    "SDDS",
    "load",
    "loadSparse",
    "loadLastRows",
    "save",
    "sdds_data_type_to_string",
    "sdds_data_type_to_short_string",
    "sdds_short_string_to_data_type",
    "demo1",
    "demo2",
    "demo3",
    "demo4",
    "demo5",
    "demo6",
    "read",
    "write",
    "SDDS_VERBOSE_PrintErrors",
    "SDDS_EXIT_PrintErrors",
    "SDDS_CHECK_OKAY",
    "SDDS_CHECK_NONEXISTENT",
    "SDDS_CHECK_WRONGTYPE",
    "SDDS_CHECK_WRONGUNITS",
    "SDDS_LONGDOUBLE",
    "SDDS_DOUBLE",
    "SDDS_REAL64",
    "SDDS_FLOAT",
    "SDDS_REAL32",
    "SDDS_LONG64",
    "SDDS_INT64",
    "SDDS_ULONG64",
    "SDDS_UINT64",
    "SDDS_LONG",
    "SDDS_INT32",
    "SDDS_ULONG",
    "SDDS_UINT32",
    "SDDS_SHORT",
    "SDDS_INT16",
    "SDDS_USHORT",
    "SDDS_UINT16",
    "SDDS_STRING",
    "SDDS_CHARACTER",
    "SDDS_NUM_TYPES",
    "SDDS_BINARY",
    "SDDS_ASCII",
    "SDDS_FLUSH_TABLE",
]

